## 例外（エラー）
例外が発生した時に実行する処理を例外処理と言います。例外処理の記述がない場合は、エラーメッセージを出力してプログラムが終了します。
## 例外の種類
例外関連のクラスは大きく分け、Errorクラス、RuntimeExceptionクラス、RuntimeExceptionクラス以外のExceptionクラスの３つがある。
- Errorクラス
例外処理を記述すべきではない、致命的なエラーを表すクラスです。
メモリ不足した時に発生するOutOfMemoryErrorクラスなどがある。
- Exceptionクラス（RuntimeExceptionクラス以外）
例外処理を記述する必要がある、一般的な例外を表すクラスです。例外を捕捉する記述がないとコンパイルエラーになります。
存在しないファイルにアクセスした時に発生するFileNotFoundExceptionクラスなどがあります。
- RuntimeExceptionクラス
例外処理を記述しなくてもコンパイルエラーにならない、プログラム実行中に発生する例外を表すクラスです。RuntimeException が発生する原因の多くは考慮不足や実装漏れによる、所謂バグと呼ばれるものです。0で割り算をした時に発生するArithmeticExceptionクラスやnullオブジェクトのメンバを参照したNullPointerExceptionクラスなどがあります。

##  例外処理
基本構文
```
try {
    tryブロック（例外が発生する可能性がある処理）
} catch (例外クラス 変数名) {
    catchブロック（例外が発生した時に実行する処理）
} catch (例外クラス 変数名) {
    catchブロック（例外が発生した時に実行する処理）
} finally {
    finallyブロック(例外発生の有無にかかわらず必ず実行する処理)
}
```
例
```
package exception;

public class Exception02 {
    public static void main(String[] args) {
        // try-catch-finally文の開始
        try {
            // tryブロック：例外が発生する可能性がある処理を記述
            System.out.println("100 ÷ 0 は？");
            // Exception01と同じく、例外が発生
            int result = 100 / 0;
            System.out.println("計算結果" + result);
        // ArithmeticExceptionクラスの例外が発生した場合の例外処理
        } catch (ArithmeticException e) {
            // 例外クラスが一致するので、例外処理が実行される
            System.out.println("例外が発生");
        } finally {
            // 例外発生しても処理を実行
            System.out.println("プログラム終了");
        }
    }
}
```

## throw文
throw文は、意図的に例外を発生させたい場合に使用。
例
```
package exception;

public class Exception03 {
    public static void main(String[] args) {
        try {
            Exception03.division(100, 0);
        } catch (ArithmeticException e) {
            System.out.println("ArithmeticException例外が発生");
        } catch (IllegalArgumentException e) {
            System.out.println("IllegalArgumentException例外が発生");
            throw e;
        }
        System.out.println("プログラム終了");
    }

    public static void division(int a, int b) {
        System.out.println(a + " ÷ " + b + " は？");
        if (b == 0) {
            throw new IllegalArgumentException("引数が不正です");
        }
        int result = a / b;
        System.out.println("計算結果" + result);
    }
}
```
実行結果
```
100 ÷ 0 は？
IllegalArgumentException例外が発生
Exception in thread "main" java.lang.IllegalArgumentException: 引数が不正です
    at exception.Exception03.division(Exception03.java:24)
    at exception.Exception03.main(Exception03.java:7)
```
## スタックトレース
実行結果で表示される「Exception in thread ・・・」以降の行は、スタックトレースという。
スタックトレースとは、例外が発生するまでにメソッドがどのような順序で呼び出されているかが記録されたもの
### 基本構文
```
// 例外インスタンスをスロー
throw 例外インスタンス;

// 例外インスタンスを生成してスロー
throw new 例外クラス;
```
例
```
package exception;

public class Exception03 {
    public static void main(String[] args) {
        try {
            // divisionメソッドを呼び出し
            Exception03.division(100, 0);
        // ArithmeticExceptionクラスの例外が発生した場合の例外処理
        } catch (ArithmeticException e) {
            // 例外クラスが一致しないので、例外処理が実行されない
            System.out.println("ArithmeticException例外が発生");
        // IllegalArgumentExceptionクラスの例外が発生した場合の例外処理
        } catch (IllegalArgumentException e) {
            // 例外処理が実行される
            System.out.println("IllegalArgumentException例外が発生");
            // キャッチした例外インスタンスをスロー
            throw e;
        }
        // finallyブロックでないので処理が実行されない
        System.out.println("プログラム終了");
    }

    public static void division(int a, int b) {
        System.out.println(a + " ÷ " + b + " は？");
        if (b == 0) {
            // 割り算で例外が発生するので、意図的にIllegalArgumentException例外をスロー
            throw new IllegalArgumentException("引数が不正です");
        }
        int result = a / b;
        System.out.println("計算結果" + result);
    }
}
```
### throws文
例外が発生した場合にcatch文を記述してメソッド内で例外処理するのではなく、例外をスローして呼び出し元に例外処理させたい場合に使用
基本構文
```
修飾子 戻り値の型 メソッド名(引数) throws 例外クラスの型 {
    // 処理
    return 戻り値;
}
```
例
```
package exception;

import java.io.FileNotFoundException;
import java.io.FileReader;

public class Exception04 {
    public static void main(String[] args) {
        try {
            // readFileメソッドを呼び出し
            Exception04.readFile("exception.txt");
        // 呼び出し元も例外処理を記述しないとコンパイルエラーになる
        } catch (FileNotFoundException e) {
            // 例外処理が実行される
            System.out.println("FileNotFoundException例外が発生");
        }
        // catch文で例外処理されるので、処理が実行される
        System.out.println("プログラム終了");
    }

    // 検査例外のFileNotFoundException例外をスロー
    public static void readFile(String fileName) throws FileNotFoundException {
        System.out.println("ファイルの読み込み開始");
        // ファイルが存在しないため例外が発生
        FileReader fr = new FileReader(fileName);
        System.out.println(fileName + "の読み込み完了");
    }
}
```

## 例外クラスの定義
Javaで予め用意されているもの以外に、自分で例外クラスを定義することもできます。基本的にはこれまで扱ってきた普通のクラスと同じくフィールドやメソッド、コンストラクタを定義することができます
例
```
// 独自の例外クラス
public class MyException extends Exception { // Exceptionクラスを継承
  // 引数なしのコンストラクタ
  public MyException() {
  }

  // エラーメッセージを受け取るコンストラクタ
  public MyException(String message) {
    super(message);
  }

  // エラーメッセージおよび発生した例外オブジェクトを受け取るコンストラクタ
  public MyException(String message, Throwable cause) {
    super(message, cause);
  }

  // エラー内容を出力するメソッド
  public void printError(String content) {
    System.out.println("エラーが発生しました:" + content);
  }
}
```
